services:

  db:
    image: postgres:15.2
    container_name: store-mate_app
    restart: always
    volumes:
      - ./db/sql/01_types.sql:/docker-entrypoint-initdb.d/01_types.sql
      - ./db/sql/02_create_schema.sql:/docker-entrypoint-initdb.d/02_create_schema.sql
      - ./db/sql/03_data.sql:/docker-entrypoint-initdb.d/03_data.sql
    environment:
      - POSTGRES_DB=storemates
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"